travis:
  secure:
    BINSTAR_TOKEN: 7RKl4WuVOISYiem1Cn1Bt0xjVU2MRqsA5MfS0czjToh6MqTkGu0PSWsROYHeNioufWW94+cNkqL48mjWJAH9tsSx/DqJyCYPo0jP/HySu6BjD/gC6jf8AUjMvpEPhnSbXbeGGaT+bPBvphSZXFFBPpPpUSicoMHIhegK3mMZ75SBbCX3zT6sM67OjGL05evgrdQuqL0o8BpYOPFUs9IkalMevbzETOtR9jmjMZ3hYWqSaktkMv6fyRuzbNWUKJebq61B1+JRfM+y5DarPDteKlFQVqGqbGHaXbNJNBnNOfF1IgOtqMw2aRk6PF/PJClkBScQkOiitG2VQmcXOwAhS2zxbvb5I4tYg9n4Zl2RMgMlKHCbFcauCZRslGxRtc8fXRbUY06/ykOkpeXdVBnqpYSwR5kAO7wA9VGEV24Vp07qQhO+EHh+nqYw8Y9JHc7SaJMO/haRj+LZGBu2Rdk0i/PU758Dr/ltDqQOOsg30gyM9JPdz6lwPBMP9Adv+/hSmRfzPH3KkRiKvkc/zCbAajYQCMj781E40qeMR7dvCbDqEpcuzGjWYd9kCc1kqOgh1YMyR81U76BlxA/aStUdCG90CuO2pCSvTcp5XoCv7dCikLAljnNbVDhrtLFqFPoeeN8tABjWSzMMoBEzuU50uGshkscwdzTuGSn8BkJZX9U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
