travis:
  secure:
    BINSTAR_TOKEN: E11nMEVs9zkEpQXoAiRpqe0L1fuANEMv/WtQpn9yE/qK4Ng0vYUTXzV3WdeBueifqsg8qmgtE2yUwaaHXcFBKYL7lBZ3A52X9QsOfkJUZIy9AcUBmFyB3jak/1MKBl/S/vKH28KBlq/FqqKonTJK8mbzD5TD+GvZpngRmIEj6IpKPtT5y3/W8TDXhT2LgajBePkLEmEATxEU4r5Dr02EzTY4NU+W/vlOUwtXYxQun5ayYdE3eEWabOIXc++0NixUCODUEy2YBUwdSyRCDhEU5GgRk7EUczNsEFt4Dpb9X4hrpzDdUAvGz+kWYB6YmSNhk283I/HcpgbagEP5mnghNjXXoU6rpcZ35ZTt6eeDiyQBC4gdjgdavYvbdP3nubUmUFY9gRkQpLTFL5BpQWSTWz3XMdF/CX0q5ouAhC9OcXHjHf/LdQeghvnSJEx9MWhgYER0WOdAl7c7j8TQQCybS8/wdw4VKKs8drKUy0TFCtSnoObsVaJv04N0vfSW4fwVv/dtBQ2SlqQ2vFi98srAXqXHj6EakN1X8ggx1uWIrX5wWygdiSd7AjgfgPLHzPJQJXQC3stedW8kEsHWeFhpRrRHXhAPz9q1L9zDRi84p58X9pWTQDpWUWQn2/DealL17PTA+xj+OCwfZwF1WfTya4+R9Vm0CBSNV9ZbLse0ySE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
